Ecom_main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from . views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home,name='home' ),
    path('search/', search,name='search' ),
    path('contact-with-us/', contact,name='contact_with_us' ),

    path('products/', products,name='products' ),
    path('detail-product/<str:id>/', detail_product,name='detail-product' ),
    
    path('store/', include('store.urls')),
    path('authentication/', include('authentication.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


urlpatterns = [
    #pip install django-shopping-cart 
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),


    path('cart/checkout/',views.checkout,name='checkout'),
    path('placeorder/',views.placeorder,name='placeorder'),

    path('success/',views.thankyou,name='success'),




]

store/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=300)
    email=models.EmailField(max_length=100)
    subject=models.CharField(max_length=300)
    message=models.TextField()
    def __str__(self):
        return self.email


class Categories(models.Model):
    name=models.CharField(max_length=300)

    def __str__(self):
        return self.name

class Brand(models.Model):
    name=models.CharField(max_length=300)
    def __str__(self):
        return self.name

class Color(models.Model):
    name=models.CharField(max_length=300)
    code=models.CharField(max_length=300)
    def __str__(self):
        return self.name


class Filter_price(models.Model):
    FIlTER_PRICE=(
        ('1000 TO 10000','1000 TO 10000'),
        ('10000 TO 20000','10000 TO 20000'),
        ('20000 TO 30000','20000 TO 30000'),
        ('30000 TO 40000','30000 TO 40000'),
        ('40000 TO 50000','40000 TO 50000'),
    )
    price=models.CharField(max_length=30,choices=FIlTER_PRICE,)
    def __str__(self):
        return self.price



class Product(models.Model):
    CONDITION=(
        ('New','New'),
        ('Old','Old'),
    )
    STOCK=(
        ('IN STOCK','IN STOCK'),
        ('OUT OF STOCK','OUT OF STOCK'),
    )
    STATUS=(
        ('Publish','Publish'),
        ('Draft','Draft'),
    )
    unique_id=models.CharField(unique=True,max_length=30,blank=True,null=True)
    image=models.ImageField(upload_to='media/Product_images/images')
    name=models.CharField(max_length=300)
    price=models.IntegerField()
    condition=models.CharField(max_length=300, choices=CONDITION)
    information=RichTextField(null=True)
    description=RichTextField(null=True)
    stoke=models.CharField(max_length=300, choices=STOCK)
    status=models.CharField(max_length=300, choices=STATUS)
    created_date=models.DateTimeField(auto_now_add=True)

    categories=models.ForeignKey(Categories,on_delete=models.CASCADE)
    brand=models.ForeignKey(Brand,on_delete=models.CASCADE)
    color=models.ForeignKey(Color,on_delete=models.CASCADE)
    filter_price=models.ForeignKey(Filter_price,on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if self.unique_id is None and self.created_date and self.id:
            self.unique_id = self.created_date.strftime('75%Y%m%d23') + str(self.id)
            
        return super().save(*args, **kwargs)
    def __str__(self):
        return self.name


class Images(models.Model):
    image=models.ImageField(upload_to='media/Product_images/images')
    product=models.ForeignKey(Product,on_delete=models.CASCADE)


class Tag(models.Model):
    name=models.CharField(max_length=30)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)


class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    country=models.CharField(max_length=100)
    address=models.TextField()
    city=models.CharField(max_length=100)
    state=models.CharField(max_length=100)
    postcode=models.IntegerField()
    phone=models.CharField(max_length=15)
    email=models.EmailField(max_length=60)
    amount=models.CharField(max_length=30)
    payment_id=models.CharField(max_length=30,null=True,blank=True)
    paid=models.BooleanField(default=False,null=True)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class OrderItem(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    product=models.CharField(max_length=100)
    image=models.ImageField(upload_to='Product_images/orders')
    quantity=models.CharField(max_length=100)
    price=models.CharField(max_length=100)
    total=models.CharField(max_length=100)
    def __str__(self):
        return self.order.user.username

templates/main/contact.html
{% extends "main/base.html" %}
{% load static %}

{% block body %}
<!-- Contact Area Start -->
<div class="contact-area">
  <div class="container">
    <div class="contact-wrapper">
      <div class="row">
        <div class="col-12">
          <div class="contact-form">
            <div class="contact-title mb-30">
              <h2 class="title">Send A Quest</h2>
            </div>


            <form class="contact-form-style" action="/contact-with-us/" method="post">
              {% csrf_token %}
              <div class="row">
                <div class="col-lg-6">
                  <input name="name" placeholder="Name*" type="text" />
                </div>
                <div class="col-lg-6">
                  <input name="email" placeholder="Email*" type="email" required/>
                </div>
                <div class="col-lg-12">
                  <input name="subject" placeholder="Subject*" type="text" required/>
                </div>
                <div class="col-lg-12 text-center">
                  <textarea name="message" placeholder="Your Message*"></textarea>
                  <button class="btn btn-primary" type="submit" required>Send Message</button>
                </div>
              </div>
            </form>


            <p class="form-messege"></p>
          </div>
        </div>
        <div class="col-12">
          <div class="contact-info">
            <div class="single-contact">
              <div class="icon-box">
                <img src="{% static 'assets/images/icons/contact-1.png' %}" alt="">
              </div>
              <div class="info-box">
                <h5 class="title">Address</h5>
                <p>Shewrapara Overbridge, <br>Mirpur Dhaka.</p>
              </div>
            </div>
            <div class="single-contact">
              <div class="icon-box">
                <img src="{% static 'assets/images/icons/contact-2.png' %}" alt="">
              </div>
              <div class="info-box">
                <h5 class="title">Phone No</h5>
                <p><a href="tel:0123456789">+8801776-068226</a></p>
                <p><a href="tel:0123456789">+8801976-068226</a></p>
              </div>
            </div>
            <div class="single-contact m-0">
              <div class="icon-box">
                <img src="{% static 'assets/images/icons/contact-3.png' %}" alt="">
              </div>
              <div class="info-box">
                <h5 class="title">Email/Web</h5>
                <p><a href="mailto:demo@example.com">hmart@gmail.com</a></p>
                <p><a href="https://www.example.com/">www.hmart.com</a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Contact Area End -->
<!-- map Area Start -->
<div class="contact-map">
    <div id="mapid">
        <div class="mapouter">
            <div class="gmap_canvas">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d10516.222924324004!2d90.37387091147076!3d23.79003792383249!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c734b13aba75%3A0xc422af0a38e9ab98!2sShewrapara%20Overbridge%2C%20Dhaka!5e0!3m2!1sen!2sbd!4v1648135224766!5m2!1sen!2sbd" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </div>
</div>
<!-- map Area End -->
{% endblock body %}

templates/main/product_detail.html
{% extends "main/base.html" %}


{% block body %}
<!-- Product Details Area Start -->
<div class="product-details-area pt-100px pb-100px">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-sm-12 col-xs-12 mb-lm-30px mb-md-30px mb-sm-30px">
        <!-- Swiper -->
        <div class="swiper-container zoom-top">
          <div class="swiper-wrapper">


            {% for p in prod.images_set.all %}
            <div class="swiper-slide">
              <img class="img-responsive m-auto" src="{{p.image.url}}" alt="detail image" style="height: 400px;">
              <a class="venobox full-preview" data-gall="myGallery"
                href="{{p.image.url}}">
                <i class="fa fa-arrows-alt" aria-hidden="true"></i>
              </a>
            </div>
            {% endfor %}


          </div>
        </div>
        <div class="swiper-container mt-20px zoom-thumbs slider-nav-style-1 small-nav">
          <div class="swiper-wrapper">


            {% for p in prod.images_set.all %}
            <div class="swiper-slide">
              <img class="img-responsive m-auto" src="{{p.image.url}}" alt="extra image">
            </div>
            {% endfor %}

          </div>
          <!-- Add Arrows -->
          <div class="swiper-buttons">
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-sm-12 col-xs-12" data-aos="fade-up" data-aos-delay="200">
        <div class="product-details-content quickview-content ml-25px">
          <h4>{{prod.name}}</h4>
          <div class="pricing-meta">
            <ul class="d-flex">
              <li class="new-price">${{prod.price}}</li>
            </ul>
          </div>
          <div class="pro-details-rating-wrap">
            <div class="rating-product">
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
            </div>
            <span class="read-review"><a class="reviews" href="#">(5 Customer Review)</a></span>
          </div>
          <p class="mt-30px">{{prod.information|safe}}</p>
          <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
            <span>Brand:</span>
            <ul class="d-flex">
              <li>
                <a href="#">{{prod.brand}}</a>
              </li>
            </ul>
          </div>
          <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
            <span>Categories: </span>
            <ul class="d-flex">
              <li>
                <a href="#">{{prod.categories}}, </a>
              </li>
            </ul>
          </div>
          <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
            <span>Tags: </span>
            <ul class="d-flex">
              <li>
                {% for tag in prod.tag_set.all %}
                  <a href="#">{{tag.name}}, </a>
                {% endfor %}
                
              </li>
            </ul>
          </div>
          <div class="pro-details-quality">
            <div class="cart-plus-minus">
              <input class="cart-plus-minus-box" type="text" name="qtybutton" value="1" />
            </div>
            <div class="pro-details-cart">
              <button class="add-cart"> Add To
                Cart</button>
            </div>
            <div class="pro-details-compare-wishlist pro-details-wishlist ">
              <a href="wishlist.html"><i class="pe-7s-like"></i></a>
            </div>
            <div class="pro-details-compare-wishlist pro-details-wishlist ">
              <a href="compare.html"><i class="pe-7s-refresh-2"></i></a>
            </div>
          </div>
        </div>
        <!-- product details description area start -->
        <div class="description-review-wrapper">
          <div class="description-review-topbar nav">
            <button data-bs-toggle="tab" data-bs-target="#des-details2">Information</button>
            <button class="active" data-bs-toggle="tab" data-bs-target="#des-details1">Description</button>
            <button data-bs-toggle="tab" data-bs-target="#des-details3">Reviews (02)</button>
          </div>
          <div class="tab-content description-review-bottom">
            <div id="des-details2" class="tab-pane">
              <div class="product-anotherinfo-wrapper text-start">
                <p>{{prod.information|safe}}</p>
              </div>
            </div>
            <div id="des-details1" class="tab-pane active">
              <div class="product-description-wrapper">
                <p>{{prod.description|safe}}</p>
              </div>
            </div>
            <div id="des-details3" class="tab-pane">
              <div class="row">
                <div class="col-lg-12">
                  <div class="review-wrapper">
                    <div class="single-review">
                      <div class="review-img">
                        <img src="assets/images/review-image/1.png" alt="" />
                      </div>
                      <div class="review-content">
                        <div class="review-top-wrap">
                          <div class="review-left">
                            <div class="review-name">
                              <h4>White Lewis</h4>
                            </div>
                            <div class="rating-product">
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                            </div>
                          </div>
                          <div class="review-left">
                            <a href="#">Reply</a>
                          </div>
                        </div>
                        <div class="review-bottom">
                          <p>
                            Vestibulum ante ipsum primis aucibus orci luctustrices posuere
                            cubilia Curae Suspendisse viverra ed viverra. Mauris ullarper
                            euismod vehicula. Phasellus quam nisi, congue id nulla.
                          </p>
                        </div>
                      </div>
                    </div>
                    <div class="single-review child-review">
                      <div class="review-img">
                        <img src="assets/images/review-image/2.png" alt="" />
                      </div>
                      <div class="review-content">
                        <div class="review-top-wrap">
                          <div class="review-left">
                            <div class="review-name">
                              <h4>White Lewis</h4>
                            </div>
                            <div class="rating-product">
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                              <i class="fa fa-star"></i>
                            </div>
                          </div>
                          <div class="review-left">
                            <a href="#">Reply</a>
                          </div>
                        </div>
                        <div class="review-bottom">
                          <p>Vestibulum ante ipsum primis aucibus orci luctustrices posuere
                            cubilia Curae Sus pen disse viverra ed viverra. Mauris ullarper
                            euismod vehicula.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="ratting-form-wrapper pl-50">
                    <h3>Add a Review</h3>
                    <div class="ratting-form">
                      <form action="#">
                        <div class="star-box">
                          <span>Your rating:</span>
                          <div class="rating-product">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-6">
                            <div class="rating-form-style">
                              <input placeholder="Name" type="text" />
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="rating-form-style">
                              <input placeholder="Email" type="email" />
                            </div>
                          </div>
                          <div class="col-md-12">
                            <div class="rating-form-style form-submit">
                              <textarea name="Your Review" placeholder="Message"></textarea>
                              <button class="btn btn-primary btn-hover-color-primary " type="submit"
                                value="Submit">Submit</button>
                            </div>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- product details description area end -->
      </div>
    </div>
  </div>
</div>
{% endblock body %}

templates/main/products.html
{% extends "main/base.html" %}


{% block body %}
<!-- Shop Page Start  -->
<div class="shop-category-area pt-100px pb-100px">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 order-lg-last col-md-12 order-md-first">
        <!-- Shop Top Area Start -->
        <div class="shop-top-bar d-flex">
          <p class="compare-product"> <span>12</span> Product Found of <span>30</span></p>
          <!-- Left Side End -->
          <div class="shop-tab nav">
            <button class="active" data-bs-target="#shop-grid" data-bs-toggle="tab">
              <i class="fa fa-th" aria-hidden="true"></i>
            </button>
            <button data-bs-target="#shop-list" data-bs-toggle="tab">
              <i class="fa fa-list" aria-hidden="true"></i>
            </button>
          </div>
          <!-- Right Side Start -->
          <div class="select-shoing-wrap d-flex align-items-center">
            <div class="shot-product">
              <p>Sort By:</p>
            </div>
            <!-- Single Wedge End -->
            <div class="header-bottom-set dropdown">
              <button class="dropdown-toggle header-action-btn" data-bs-toggle="dropdown">Default <i
                  class="fa fa-angle-down"></i></button>
              <ul class="dropdown-menu dropdown-menu-right">

                <li><a class="dropdown-item" href="/products/{% for p in product %}?AtoZ={{p.id}} {% endfor %}">Name, A
                    to Z</a></li>

                <li><a class="dropdown-item" href="/products/{% for p in product %}?ZtoA={{p.id}} {% endfor %}">Name, Z
                    to A</a></li>

                <li><a class="dropdown-item"
                    href="/products/{% for p in product %}?priceLowToHigh={{p.id}} {% endfor %}">Price, low to high</a>
                </li>

                <li><a class="dropdown-item"
                    href="/products/{% for p in product %}?priceHighToLow={{p.id}} {% endfor %}">Price, high to low</a>
                </li>

                <li><a class="dropdown-item" href="/products/{% for p in product %}?new={{p.id}} {% endfor %}">Sort By
                    new</a></li>

                <li><a class="dropdown-item" href="/products/{% for p in product %}?old={{p.id}} {% endfor %}">Sort By
                    old</a></li>
              </ul>
            </div>
            <!-- Single Wedge Start -->
          </div>
          <!-- Right Side End -->
        </div>
        <!-- Shop Top Area End -->
        <!-- Shop Bottom Area Start -->
        <div class="shop-bottom-area">
          <!-- Tab Content Area Start -->
          <div class="row">
            <div class="col">
              <div class="tab-content">
                <div class="tab-pane fade show active" id="shop-grid">
                  <div class="row mb-n-30px">

                    {% for p in product %}
                    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 mb-30px">
                      <!-- Single Product -->
                      <div class="product">
                        <span class="badges">
                          <span class="new">{{p.condition}}</span>
                        </span>
                        <div class="thumb">
                          <a href="single-product.html" class="image">
                            <img src="{{p.image.url}}" alt="Product" style="height:280px" />
                            <img class="hover-image" src="{{p.image.url}}" alt="Product" />
                          </a>
                        </div>
                        <div class="content"> <br>
                          <span class="category"><a href="#">{{p.categories}}</a></span>
                          <h5 class="title"><a href="#">{{p.name|truncatechars:20}}
                            </a>
                          </h5>
                          <span class="price">
                            <span class="new">${{p.price}}</span>
                          </span>
                        </div>
                        <div class="actions">
                          <button title="Add To Cart" class="action add-to-cart" data-bs-toggle="modal"
                            data-bs-target="#exampleModal-Cart-{{forloop.counter}}"><i class="pe-7s-shopbag"></i></button>
                          <button class="action wishlist" title="Wishlist" data-bs-toggle="modal"
                            data-bs-target="#exampleModal-Wishlist"><i class="pe-7s-like"></i></button>
                          <button class="action quickview" data-link-action="quickview" title="Quick view"
                            data-bs-toggle="modal" data-bs-target="#exampleModal-{{forloop.counter}}"><i class="pe-7s-look"></i></button>
                          <button class="action compare" title="Compare" data-bs-toggle="modal"
                            data-bs-target="#exampleModal-Compare"><i class="pe-7s-refresh-2"></i></button>
                        </div>
                      </div>
                    </div>
                    {% endfor %}

                  </div>
                </div>
                <div class="tab-pane fade mb-n-30px" id="shop-list">

                  {% for p in product %}
                  <div class="shop-list-wrapper mb-30px">
                    <div class="row">
                      <div class="col-md-5 col-lg-5 col-xl-4 mb-lm-30px">
                        <div class="product">
                          <div class="thumb">
                            <a href="single-product.html" class="image">
                              <img src="{{p.image.url}}" alt="Product" />
                              <img class="hover-image" src="{{p.image.url}}" alt="Product" />
                            </a>
                            <span class="badges">
                              <span class="new">{{p.condition}}</span>
                            </span>
                          </div>
                        </div>
                      </div>
                      <div class="col-md-7 col-lg-7 col-xl-8">
                        <div class="content-desc-wrap">
                          <div class="content">
                            <span class="category"><a href="#">{{p.categories}}</a></span>
                            <h5 class="title"><a href="single-product.html">{{p.name}}</a></h5>
                            <p>{{p.description|truncatechars:500|safe}}</p>
                          </div>
                          <div class="box-inner">
                            <span class="price">
                              <span class="new">${{p.price}}</span>
                            </span>
                            <div class="actions">
                              <button title="Add To Cart" class="action add-to-cart" data-bs-toggle="modal"
                                data-bs-target="#exampleModal-Cart-{{forloop.counter}}"><i class="pe-7s-shopbag"></i></button>

                              <button class="action wishlist" title="Wishlist" data-bs-toggle="modal"
                                data-bs-target="#exampleModal-Wishlist"><i class="pe-7s-like"></i></button>

                              <button class="action quickview" data-link-action="quickview" title="Quick view"data-bs-toggle="modal" data-bs-target="#exampleModal-{{forloop.counter}}"><i
                                  class="pe-7s-look"></i></button>

                              <button class="action compare" title="Compare" data-bs-toggle="modal"
                                data-bs-target="#exampleModal-Compare"><i class="pe-7s-refresh-2"></i></button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endfor %}

                </div>
              </div>
            </div>
          </div>
          <!-- Tab Content Area End -->
          <!--  Pagination Area Start -->
          <div class="pro-pagination-style text-center text-lg-end" data-aos="fade-up" data-aos-delay="200">
            <div class="pages">
              <ul>
                <li class="li"><a class="page-link" href="#"><i class="fa fa-angle-left"></i></a>
                </li>
                <li class="li"><a class="page-link" href="#">1</a></li>
                <li class="li"><a class="page-link active" href="#">2</a></li>
                <li class="li"><a class="page-link" href="#">3</a></li>
                <li class="li"><a class="page-link" href="#"><i class="fa fa-angle-right"></i></a>
                </li>
              </ul>
            </div>
          </div>
          <!--  Pagination Area End -->
        </div>
        <!-- Shop Bottom Area End -->
      </div>
      <!-- Sidebar Area Start -->
      <div class="col-lg-3 order-lg-first col-md-12 order-md-last">
        <div class="shop-sidebar-wrap">
          <!-- Sidebar single item -->
          <div class="sidebar-widget">
            <h4 class="sidebar-title">Top Categories</h4>
            <div class="sidebar-widget-category">
              <ul>

                <li><a href="/products/" class="selected m-0"> All</a></li>
                {% for cat in category %}
                <li><a href="/products/?categories={{cat.id}}" class="selected m-0"> {{cat.name}}</a></li>
                {% endfor %}

              </ul>
            </div>
          </div>
          <!-- Sidebar single item -->
          <div class="sidebar-widget mt-8">
            <h4 class="sidebar-title">Price Filter</h4>
            <div class="price-filter">
              <div class="price-slider-amount">

                {% for f in filter_price %}
                <li><a href="/products/?filter_price={{f.id}}" class="selected m-0"> {{f.price}}</a></li>
                {% endfor %}

              </div>

            </div>
          </div>
          <!-- Sidebar single item -->
          <div class="sidebar-widget">
            <h4 class="sidebar-title">Color</h4>
            <div class="sidebar-widget-color">
              <ul class="d-flex flex-wrap">

                {% for c in color %}
                <li><a href="/products/?color={{c.id}}" style="background-color:{{c.code}}"></a></li>
                {% endfor %}

              </ul>
            </div>
          </div>
          <div class="sidebar-widget">
            <h4 class="sidebar-title">Brands</h4>
            <div class="sidebar-widget-brand">
              <ul>

                <li><a href="/products/" class="selected m-0"> All Brands</a></li>
                {% for b in brand %}
                <li><a href="/products/?brand={{b.id}}" class="">{{b.name}}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <!-- Sidebar single item -->
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Shop Page End  -->
{% endblock body %}